[package]
name = "sentry-actix"
version = "0.17.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://github.com/getsentry/sentry-rust"
documentation = "https://docs.rs/sentry-actix"
description = """
Sentry client extension for actix-web
"""
edition = "2018"

[features]
default = ["with_sentry_default"]
with_sentry_default = [
    "sentry/with_client_implementation",
    "sentry/with_default_transport",
    "sentry/with_panic",
    "sentry/with_failure",
    "sentry/with_log",
    "sentry/with_env_logger",
    "sentry/with_device_info",
    "sentry/with_rust_info",
    "sentry/with_native_tls"
]

[dependencies]
actix-web = { version = "2.0.0", default-features = false }
sentry = { version = "0.17.0", path = "../../", default-features = false }
failure = "0.1.3"
fragile = "0.3.0"
